package GUI.cards;

import GUI.*;

public class PlayerNameCard extends javax.swing.JPanel {

    // Properties ==============================================================
    private final MainFrame frame;
    
// Constructor =============================================================
    public PlayerNameCard(MainFrame frame) {
        this.frame = frame;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabelPlayerName = new javax.swing.JLabel();
        jButtonEnterName = new javax.swing.JButton();

        jLabelPlayerName.setText("Please enter your name in the box below...");

        jButtonEnterName.setText("Submit");
        jButtonEnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPlayerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jButtonEnterName))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnterName)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterNameActionPerformed
        String name = jTextField1.getText().trim();

        // Validation
        if (name.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a name!", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!name.matches("[a-zA-Z ]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Name must only contain letters and spaces.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (name.length() < 2 || name.length() > 20) {
            javax.swing.JOptionPane.showMessageDialog(this, "Name must be between 2 and 20 characters.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Save name directly to the player
        frame.getGame().getPlayer().setName(name);

        // Greet player
        javax.swing.JOptionPane.showMessageDialog(this, "Welcome, " + name + "!");
        
        // Switch to StartCard
        frame.getCardsPanel().showCard("StartCard");
    }//GEN-LAST:event_jButtonEnterNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnterName;
    private javax.swing.JLabel jLabelPlayerName;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
