package GUI.cards;

import GUI.*;
import LOGIC.*;
import javax.swing.JOptionPane;

public class StartCard extends javax.swing.JPanel {

    // PROPERTIES ==============================================================
    private final MainFrame frame;
    private final Game game;

    // CONSTRUCTOR =============================================================
    public StartCard(MainFrame frame) {
        this.frame = frame;
        this.game = frame.getGame();
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNewMap = new javax.swing.JButton();
        buttonLoadMap = new javax.swing.JButton();

        buttonNewMap.setText("New Map");
        buttonNewMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewMapActionPerformed(evt);
            }
        });

        buttonLoadMap.setText("Load Map");
        buttonLoadMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(buttonNewMap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLoadMap)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewMap)
                    .addComponent(buttonLoadMap))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        buttonNewMap.getAccessibleContext().setAccessibleName("buttonNewMap");
        buttonLoadMap.getAccessibleContext().setAccessibleName("buttonLoadMap");
    }// </editor-fold>//GEN-END:initComponents

    // Generate a new map
    private void buttonNewMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewMapActionPerformed
        game.forceGenerateNewMap(); // Force new map and set port
        frame.getCardsPanel().createGameCards(); // Create cards now that game is ready
        frame.getCardsPanel().showCard("PortCard");
        frame.getPlayerPanel().updateWindDisplay();
    }//GEN-LAST:event_buttonNewMapActionPerformed

    // Generate a loaded map
    private void buttonLoadMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadMapActionPerformed
        boolean loaded = game.initialiseMap(); // Try load, fallback to generate

        // No load found
        if (!loaded) {
            JOptionPane.showMessageDialog(this,
                "No saved map found. A new one has been generated.",
                "Map Not Found",
                JOptionPane.INFORMATION_MESSAGE);
        }

        frame.getCardsPanel().createGameCards();
        frame.getCardsPanel().showCard("PortCard");
        frame.getPlayerPanel().updateWindDisplay();
    }//GEN-LAST:event_buttonLoadMapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLoadMap;
    private javax.swing.JButton buttonNewMap;
    // End of variables declaration//GEN-END:variables
}
