package GUI;
import LOGIC.*;


public class CharacterOverlayPanel extends javax.swing.JPanel {

    private Player player;
    
    /**
     * Creates new form CharacterOverlayPanel
     */
    public CharacterOverlayPanel(Player player) {
        this.player = player;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPlayerName = new javax.swing.JLabel();
        labelPlayerGold = new javax.swing.JLabel();

        labelPlayerName.setText(player.getName());

        labelPlayerGold.setText("Gold: " + String.valueOf(player.getGold()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPlayerGold)
                    .addComponent(labelPlayerName))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(labelPlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPlayerGold)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Update Gold Label
    public void updateGold(int gold) {
        labelPlayerGold.setText("Gold: " + String.valueOf(gold));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPlayerGold;
    private javax.swing.JLabel labelPlayerName;
    // End of variables declaration//GEN-END:variables
}
