package GUI;

public class PortPanel extends javax.swing.JPanel {

    // ========== PROPERTIES ==========
    private MainPanel mainPanel;
    
    // ========== CONSTRUCTOR ==========
    public PortPanel(MainPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
    }

    // ========== AUTO-GENERATED =========
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPort = new javax.swing.JLabel();
        buttonViewMarket = new javax.swing.JButton();
        buttonViewShipyard = new javax.swing.JButton();
        buttonTravel = new javax.swing.JButton();

        labelPort.setText("WELCOME TO THE PORT");

        buttonViewMarket.setText("View Market");

        buttonViewShipyard.setText("View Shipyard");

        buttonTravel.setText("Travel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPort)
                    .addComponent(buttonViewMarket)
                    .addComponent(buttonViewShipyard)
                    .addComponent(buttonTravel))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonViewMarket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonViewShipyard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTravel)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // ========== METHODS ==========
    
    
    // ========== AUTO-GENERATED ==========
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTravel;
    private javax.swing.JButton buttonViewMarket;
    private javax.swing.JButton buttonViewShipyard;
    private javax.swing.JLabel labelPort;
    // End of variables declaration//GEN-END:variables
}
