
package GUI.cards;

import GUI.*;
import LOGIC.*;

import javax.swing.DefaultListModel;

public class MarketPanel extends javax.swing.JPanel {

    // ========== PROPERTIES ==========
    private CardsPanel cardsPanel;
    private Game game;

    // ========== CONSTRUCTOR ==========
    public MarketPanel(CardsPanel cardsPanel, Game game) 
    {
        initComponents();
        
        this.game = game;
        this.cardsPanel = cardsPanel;
        
        
        DefaultListModel<String> dlm = new DefaultListModel();
        
        for(Good g : game.getPort().getMarket().getGoods())
        {
            dlm.addElement(g.getName());
        }
        
        listGoods.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelPortMarket = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGoods = new javax.swing.JList<>();

        labelPortMarket.setText("Port Market");
        labelPortMarket.setName("labelPortNameMarket"); // NOI18N

        jScrollPane1.setViewportView(listGoods);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(labelPortMarket))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPortMarket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPortMarket;
    private javax.swing.JList<String> listGoods;
    // End of variables declaration//GEN-END:variables
}
